
# 等待 MySQL 服务启动
sleep 30

# 使用环境变量执行 MySQL 命令
mysql -h 127.0.0.1 -P 3306 -u${MYSQL_USER} -p${MYSQL_PASSWORD} <<EOF
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'${CURRENT_IP}' IDENTIFIED BY '${MYSQL_PASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF